my_string = input("Введите название университета ")
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ",""))
print("Введите название университета ".replace(" ",""))
print(my_string[0])
print("Введите название университета "[0])
print(my_string[-1])
print("Введите название университета"[-1])
